// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/assistant/pkg/records/extractor (interfaces: ContentExtractor)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_extractor.go -mock_names=ContentExtractor=MockContentExtractor -package=mocks . ContentExtractor
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	records "github.com/kazemisoroush/assistant/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockContentExtractor is a mock of ContentExtractor interface.
type MockContentExtractor struct {
	ctrl     *gomock.Controller
	recorder *MockContentExtractorMockRecorder
	isgomock struct{}
}

// MockContentExtractorMockRecorder is the mock recorder for MockContentExtractor.
type MockContentExtractorMockRecorder struct {
	mock *MockContentExtractor
}

// NewMockContentExtractor creates a new mock instance.
func NewMockContentExtractor(ctrl *gomock.Controller) *MockContentExtractor {
	mock := &MockContentExtractor{ctrl: ctrl}
	mock.recorder = &MockContentExtractorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentExtractor) EXPECT() *MockContentExtractorMockRecorder {
	return m.recorder
}

// Extract mocks base method.
func (m *MockContentExtractor) Extract(ctx context.Context, rawContent string) (records.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Extract", ctx, rawContent)
	ret0, _ := ret[0].(records.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Extract indicates an expected call of Extract.
func (mr *MockContentExtractorMockRecorder) Extract(ctx, rawContent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extract", reflect.TypeOf((*MockContentExtractor)(nil).Extract), ctx, rawContent)
}
