// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/assistant/pkg/records/service (interfaces: Service)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_service.go -mock_names=Service=MockService -package=mocks . Service
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	records "github.com/kazemisoroush/assistant/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
	isgomock struct{}
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockService) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockService)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockService) GetByID(ctx context.Context, id string) (records.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(records.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockServiceMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockService)(nil).GetByID), ctx, id)
}

// Ingest mocks base method.
func (m *MockService) Ingest(ctx context.Context, rec records.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ingest", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ingest indicates an expected call of Ingest.
func (mr *MockServiceMockRecorder) Ingest(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ingest", reflect.TypeOf((*MockService)(nil).Ingest), ctx, rec)
}

// List mocks base method.
func (m *MockService) List(ctx context.Context, recType records.RecordType) ([]records.Record, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, recType)
	ret0, _ := ret[0].([]records.Record)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockServiceMockRecorder) List(ctx, recType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockService)(nil).List), ctx, recType)
}

// Search mocks base method.
func (m *MockService) Search(ctx context.Context, query string, filters map[string]any, limit int) ([]records.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, filters, limit)
	ret0, _ := ret[0].([]records.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockServiceMockRecorder) Search(ctx, query, filters, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockService)(nil).Search), ctx, query, filters, limit)
}

// Update mocks base method.
func (m *MockService) Update(ctx context.Context, rec records.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockServiceMockRecorder) Update(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockService)(nil).Update), ctx, rec)
}
