// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/assistant/pkg/records/knowledgebase (interfaces: VectorStore)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_vectorstore.go -mock_names=VectorStore=MockVectorStore -package=mocks . VectorStore
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	records "github.com/kazemisoroush/assistant/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockVectorStore is a mock of VectorStore interface.
type MockVectorStore struct {
	ctrl     *gomock.Controller
	recorder *MockVectorStoreMockRecorder
	isgomock struct{}
}

// MockVectorStoreMockRecorder is the mock recorder for MockVectorStore.
type MockVectorStoreMockRecorder struct {
	mock *MockVectorStore
}

// NewMockVectorStore creates a new mock instance.
func NewMockVectorStore(ctrl *gomock.Controller) *MockVectorStore {
	mock := &MockVectorStore{ctrl: ctrl}
	mock.recorder = &MockVectorStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorStore) EXPECT() *MockVectorStoreMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockVectorStore) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockVectorStoreMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVectorStore)(nil).Close))
}

// Delete mocks base method.
func (m *MockVectorStore) Delete(ctx context.Context, recID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, recID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVectorStoreMockRecorder) Delete(ctx, recID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVectorStore)(nil).Delete), ctx, recID)
}

// Index mocks base method.
func (m *MockVectorStore) Index(ctx context.Context, rec *records.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockVectorStoreMockRecorder) Index(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockVectorStore)(nil).Index), ctx, rec)
}

// Search mocks base method.
func (m *MockVectorStore) Search(ctx context.Context, query string, limit int) ([]records.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit)
	ret0, _ := ret[0].([]records.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockVectorStoreMockRecorder) Search(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockVectorStore)(nil).Search), ctx, query, limit)
}
