// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/assistant/pkg/records/knowledgebase (interfaces: VectorStorage)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_vectorstorage.go -mock_names=VectorStorage=MockVectorStorage -package=mocks . VectorStorage
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	records "github.com/kazemisoroush/assistant/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockVectorStorage is a mock of VectorStorage interface.
type MockVectorStorage struct {
	ctrl     *gomock.Controller
	recorder *MockVectorStorageMockRecorder
	isgomock struct{}
}

// MockVectorStorageMockRecorder is the mock recorder for MockVectorStorage.
type MockVectorStorageMockRecorder struct {
	mock *MockVectorStorage
}

// NewMockVectorStorage creates a new mock instance.
func NewMockVectorStorage(ctrl *gomock.Controller) *MockVectorStorage {
	mock := &MockVectorStorage{ctrl: ctrl}
	mock.recorder = &MockVectorStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVectorStorage) EXPECT() *MockVectorStorageMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockVectorStorage) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockVectorStorageMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockVectorStorage)(nil).Close))
}

// Delete mocks base method.
func (m *MockVectorStorage) Delete(ctx context.Context, recID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, recID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockVectorStorageMockRecorder) Delete(ctx, recID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockVectorStorage)(nil).Delete), ctx, recID)
}

// Index mocks base method.
func (m *MockVectorStorage) Index(ctx context.Context, rec records.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Index", ctx, rec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Index indicates an expected call of Index.
func (mr *MockVectorStorageMockRecorder) Index(ctx, rec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Index", reflect.TypeOf((*MockVectorStorage)(nil).Index), ctx, rec)
}

// Search mocks base method.
func (m *MockVectorStorage) Search(ctx context.Context, query string, limit int) ([]records.SearchResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", ctx, query, limit)
	ret0, _ := ret[0].([]records.SearchResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockVectorStorageMockRecorder) Search(ctx, query, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockVectorStorage)(nil).Search), ctx, query, limit)
}
