// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/assistant/pkg/records/source (interfaces: Source)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/mock_source.go -mock_names=Source=MockSource -package=mocks . Source
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	records "github.com/kazemisoroush/assistant/pkg/records"
	gomock "go.uber.org/mock/gomock"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockSource) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSource)(nil).Name))
}

// Scrape mocks base method.
func (m *MockSource) Scrape(ctx context.Context, basePath string) (<-chan records.Record, <-chan error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Scrape", ctx, basePath)
	ret0, _ := ret[0].(<-chan records.Record)
	ret1, _ := ret[1].(<-chan error)
	return ret0, ret1
}

// Scrape indicates an expected call of Scrape.
func (mr *MockSourceMockRecorder) Scrape(ctx, basePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Scrape", reflect.TypeOf((*MockSource)(nil).Scrape), ctx, basePath)
}
