// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kazemisoroush/assistant/pkg/records/discovery (interfaces: Discovery)
//
// Generated by this command:
//
//	mockgen -destination=./mocks/discovery_mock.go -package=mocks github.com/kazemisoroush/assistant/pkg/records/discovery Discovery
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockDiscovery is a mock of Discovery interface.
type MockDiscovery struct {
	ctrl     *gomock.Controller
	recorder *MockDiscoveryMockRecorder
	isgomock struct{}
}

// MockDiscoveryMockRecorder is the mock recorder for MockDiscovery.
type MockDiscoveryMockRecorder struct {
	mock *MockDiscovery
}

// NewMockDiscovery creates a new mock instance.
func NewMockDiscovery(ctrl *gomock.Controller) *MockDiscovery {
	mock := &MockDiscovery{ctrl: ctrl}
	mock.recorder = &MockDiscoveryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDiscovery) EXPECT() *MockDiscoveryMockRecorder {
	return m.recorder
}

// Discover mocks base method.
func (m *MockDiscovery) Discover(ctx context.Context, prompt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Discover", ctx, prompt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Discover indicates an expected call of Discover.
func (mr *MockDiscoveryMockRecorder) Discover(ctx, prompt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Discover", reflect.TypeOf((*MockDiscovery)(nil).Discover), ctx, prompt)
}
